### ISSUE TITLE
uploading the data to osf

### ISSUE THREAD

**Issue by maikia** [ramp-kits/stroke#4]
We decided to use `_upload_data.py` and `download_data.py` from meg challenge as templates for uploading and downloading the data (not yet defined in the docs of ramp.studio).

atm the data is being compressed into `.tar.gz` to be stored on OSF. This works very well for the smaller datasets, however for large datasets such as of the `stroke challenge` (~9GB after comrpession) this leads to errors.

**Comment by maikia** [comment]
@tomMoral what would be your idea to deal with that? (not compressing could probably work as we would upload smaller files but not very clean perhaps)

**Comment by maikia** [comment]
For now I loaded private data to S3 on AWS from where it is loaded into the AMI, and public data is on osf

**Comment by tomMoral** [comment]
The private data is much larger?

**Comment by maikia** [comment]
Yes, it is larger

**Comment by tomMoral** [comment]
I would say that if we could keep everything in a single place, this is the best.
So I would probably go for multiple compressed archives, 1Gb each?

**Comment by AlexandreHutton** [comment]
I'm closing this issue because this kit is no longer using OSF.
