### ISSUE TITLE
moved modules to pip dependencies

### ISSUE THREAD

**Issue by frcaud** [ramp-kits/stroke#7]
https://github.com/ramp-kits/stroke/blob/cce417a28b738cdd5b6623746437591cbe93b80a/environment.yml#L12

It worked better for me to move torch, wget and pybids to pip dependencies.

**Comment by agramfort** [comment]
CIs should tell us what works best :)

**Comment by frcaud** [comment]
well as a matter of fact, CI told us that torch and bids were in red ;)
